"""empty message

Revision ID: 53170a332deb
Revises: 
Create Date: 2019-06-02 13:39:37.017076

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53170a332deb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('drug', 'name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.alter_column('drug', 'num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('drug', 'price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('drug', 'pro',
               existing_type=mysql.VARCHAR(length=32),
               nullable=False)
    op.create_unique_constraint(None, 'drug', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'drug', type_='unique')
    op.alter_column('drug', 'pro',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    op.alter_column('drug', 'price',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('drug', 'num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('drug', 'name',
               existing_type=mysql.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###
